### ISSUE TITLE
stop work in jupyter 5. and ipywidgets 6.0.0 ?

### ISSUE THREAD

**Issue by WeiLiPenguin** [gabrielelanaro/chemview#41]
Hi,

install jupyter from conda
everything stop working ....

Please help 

Best Regards!

**Comment by gabrielelanaro** [comment]
Hi! I just pushed a small fix, let me know if that works for you

**Comment by WeiLiPenguin** [comment]
Hi, 
Thank you!

But still not work for me. 

I use python2, is that the problem? 

I try
create new conda env 
and clone the chemview
```
cd chemview
pip install -e .
conda install widgetsnbextension
jupyter nbextension enable widgetsnbextension --user --py
jupyter nbextension install --py --symlink chemview --user
jupyter nbextension enable --py  chemview
```

Best Regards!

**Comment by gabrielelanaro** [comment]
I tested the QuickStart.ipynb on Python 2, and it's going ok, does it work for you as well?

Which feature specifically doesn't work?

**Comment by WeiLiPenguin** [comment]
Hi, 
```
jupyter                   1.0.0                    py27_3 
jupyter_client            4.4.0                    py27_0 
jupyter_console           5.0.0                    py27_0 
jupyter_core              4.2.1                    py27_0 
ipywidgets                6.0.0                    py27_0
widgetsnbextension        2.0.0                    py27_0
```


*Embed widgets*:
```
<script src="https://unpkg.com/jupyter-js-widgets@~2.1.4/dist/embed.js"></script>
<script type="application/vnd.jupyter.widget-state+json">
{
    "version_major": 1,
    "version_minor": 0,
    "state": {
        "ed0ca03368d643098e77a36059d76258": {
            "model_name": "LayoutModel",
            "model_module": "jupyter-js-widgets",
            "model_module_version": "~2.1.4",
            "state": {
                "_model_module_version": "~2.1.4",
                "_view_module_version": "~2.1.4"
            }
        },
        "67bbbebd55a44b51a8c0c2ebdc33d4ba": {
            "model_name": "ChemviewModel",
            "model_module": "jupyter-widget-chemview",
            "model_module_version": "*",
            "state": {
                "_dom_classes": [],
                "msg_throttle": 1,
                "static_moving": false,
                "_model_module_version": "*",
                "height": 300,
                "width": 300,
                "_view_module_version": "*",
                "background": 0,
                "loaded": false,
                "layout": "IPY_MODEL_ed0ca03368d643098e77a36059d76258",
                "camera_str": ""
            }
        },
        "0178d77ee3754af1a5a65a96fd109b3a": {
            "model_name": "LayoutModel",
            "model_module": "jupyter-js-widgets",
            "model_module_version": "~2.1.4",
            "state": {
                "_model_module_version": "~2.1.4",
                "_view_module_version": "~2.1.4"
            }
        },
        "529499d6caaa4de889c3fee522651c31": {
            "model_name": "ChemviewModel",
            "model_module": "jupyter-widget-chemview",
            "model_module_version": "*",
            "state": {
                "_dom_classes": [],
                "msg_throttle": 1,
                "static_moving": false,
                "_model_module_version": "*",
                "height": 300,
                "width": 300,
                "_view_module_version": "*",
                "background": 0,
                "loaded": false,
                "layout": "IPY_MODEL_0178d77ee3754af1a5a65a96fd109b3a",
                "camera_str": ""
            }
        }
    }
}
</script>
```

`"loaded": false,`

should it be load?

Best Regards!

**Comment by singletS** [comment]
This problem (nothing being rendered in the notebook) is reproducible for firefox51-linux in a new conda environment with the following packages
```
jupyter                   1.0.0                    py35_3  
jupyter_client            5.0.0                    py35_0    
jupyter_core              4.3.0                    py35_0 
ipywidgets                6.0.0                    py35_0
widgetsnbextension        2.0.0                    py35_0
chemview                  0.7                      py35_0    gabrielelanaro
chemlab                   1.1                      py35_0    gabrielelanaro
```
Running demo snippets such as the water molecule balls-and-sticks gives the warning
```
anaconda3/envs/chemview/lib/python3.5/site-packages/traitlets/traitlets.py:567: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  silent = bool(old_value == new_value)
```

**Comment by gabrielelanaro** [comment]
Is it possible to know the traceback from the javascript console? I have some users find out that the  browser supported only WebGL version 1 and that was the culprit.

**Comment by psychemedia** [comment]
I've just noticed an install error using `pip` with the extension package:

```
KeyError: 'The Python module chemview is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method
```

**Comment by hainm** [comment]
not want to compete with chemview here but just in case you all want an alternative package:

https://github.com/arose/nglview
